CREATE TABLE LABEL (
    ID int NOT NULL AUTO_INCREMENT,
    COLOR varchar(25) NOT NULL,
    CARD_ID int NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (CARD_ID) REFERENCES CARD (ID)
  );
ALTER TABLE LABEL AUTO_INCREMENT=20000;
COMMIT;