CREATE TABLE REMARK (
    ID int NOT NULL AUTO_INCREMENT,
    CONTENT varchar(50) NOT NULL,
    CARD_ID int NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (CARD_ID) REFERENCES CARD (ID)
  );
ALTER TABLE REMARK AUTO_INCREMENT=15000;
COMMIT;