CREATE TABLE ROLL (
    ID int NOT NULL AUTO_INCREMENT,
    NAME varchar(50) NOT NULL,
    BOARD_ID int NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (BOARD_ID) REFERENCES BOARD (ID)
  );
ALTER TABLE ROLL AUTO_INCREMENT=1000;

COMMIT;